---
dependency:
  name: galaxy
driver:
    name: podman
platforms:
  - name: centos
    box: centos
#    instance_raw_config_args:
#      - "vm.network 'forwarded_port', guest: 80, host: 8088"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
